/**
 * The Cyrest API
 * Auto genertaed Cyrest API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


const ApiClient = require('./ApiClient'),
 BaseErrorResponseSimple = require('./model/BaseErrorResponseSimple'),
 BaseNormalResponse = require('./model/BaseNormalResponse'),
 UserCorporation = require('./model/UserCorporation'),
 UserForgotPayload = require('./model/UserForgotPayload'),
 UserLoginPayload = require('./model/UserLoginPayload'),
 UserPersonal = require('./model/UserPersonal'),
 UserRegistrationPayload = require('./model/UserRegistrationPayload'),
 UserResponseLoginOK = require('./model/UserResponseLoginOK'),
 VersionVersion = require('./model/VersionVersion'), MiscApi = require('./api/MiscApi'), UserApi = require('./api/UserApi')


  /**
   * Auto_genertaed_Cyrest_API.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var TheCyrestApi = require('index'); // See note below*.
   * var xxxSvc = new TheCyrestApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new TheCyrestApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new TheCyrestApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new TheCyrestApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The BaseErrorResponseSimple model constructor.
     * @property {module:model/BaseErrorResponseSimple}
     */
    BaseErrorResponseSimple: BaseErrorResponseSimple,
    /**
     * The BaseNormalResponse model constructor.
     * @property {module:model/BaseNormalResponse}
     */
    BaseNormalResponse: BaseNormalResponse,
    /**
     * The UserCorporation model constructor.
     * @property {module:model/UserCorporation}
     */
    UserCorporation: UserCorporation,
    /**
     * The UserForgotPayload model constructor.
     * @property {module:model/UserForgotPayload}
     */
    UserForgotPayload: UserForgotPayload,
    /**
     * The UserLoginPayload model constructor.
     * @property {module:model/UserLoginPayload}
     */
    UserLoginPayload: UserLoginPayload,
    /**
     * The UserPersonal model constructor.
     * @property {module:model/UserPersonal}
     */
    UserPersonal: UserPersonal,
    /**
     * The UserRegistrationPayload model constructor.
     * @property {module:model/UserRegistrationPayload}
     */
    UserRegistrationPayload: UserRegistrationPayload,
    /**
     * The UserResponseLoginOK model constructor.
     * @property {module:model/UserResponseLoginOK}
     */
    UserResponseLoginOK: UserResponseLoginOK,
    /**
     * The VersionVersion model constructor.
     * @property {module:model/VersionVersion}
     */
    VersionVersion: VersionVersion,
    /**
     * The MiscApi service constructor.
     * @property {module:api/MiscApi}
     */
    MiscApi: MiscApi,
    /**
     * The UserApi service constructor.
     * @property {module:api/UserApi}
     */
    UserApi: UserApi
  };

module.exports = exports;
