/**
 * The Cyrest API
 * Auto genertaed Cyrest API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

    // CommonJS-like environments that support module.exports, like Node.
    const ApiClient = require('../ApiClient')
    





  /**
   * The VersionVersion model module.
   * @module model/VersionVersion
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>VersionVersion</code>.
   * @alias module:model/VersionVersion
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>VersionVersion</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VersionVersion} obj Optional instance to populate.
   * @return {module:model/VersionVersion} The populated <code>VersionVersion</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('build_date')) {
        obj['build_date'] = ApiClient.convertToType(data['build_date'], 'String');
      }
      if (data.hasOwnProperty('build_number')) {
        obj['build_number'] = ApiClient.convertToType(data['build_number'], 'Integer');
      }
      if (data.hasOwnProperty('commit_date')) {
        obj['commit_date'] = ApiClient.convertToType(data['commit_date'], 'String');
      }
      if (data.hasOwnProperty('hash')) {
        obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
      }
      if (data.hasOwnProperty('short_hash')) {
        obj['short_hash'] = ApiClient.convertToType(data['short_hash'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} build_date
   */
  exports.prototype['build_date'] = undefined;
  /**
   * @member {Integer} build_number
   */
  exports.prototype['build_number'] = undefined;
  /**
   * @member {String} commit_date
   */
  exports.prototype['commit_date'] = undefined;
  /**
   * @member {String} hash
   */
  exports.prototype['hash'] = undefined;
  /**
   * @member {String} short_hash
   */
  exports.prototype['short_hash'] = undefined;



  module.exports = exports;



