/**
 * The Cyrest API
 * Auto genertaed Cyrest API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

    const ApiClient = require('../ApiClient'),
     VersionVersion = require('../model/VersionVersion');

  /**
   * Misc service.
   * @module api/MiscApi
   * @version 1.0.0
   */

  /**
   * Constructs a new MiscApi. 
   * @alias module:api/MiscApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the miscVersionGet operation.
     * @callback module:api/MiscApi~miscVersionGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VersionVersion} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getVersion get the version information
     * @param {module:api/MiscApi~miscVersionGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VersionVersion}
     */
    this.miscVersionGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = VersionVersion;

      return this.apiClient.callApi(
        '/misc/version', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  module.exports = exports;
